[tool.black]
line-length = 99
target-version = ['py36']

[tool.codespell]
count = ''
ignore-words-list = 'nervana,cconfiguration'
quiet-level = 3
skip = '*.dasm,*.map,./rtldev,./.mypy_cache,./sdk,./venv,./.git,./super-linter.log'
ignore-regex = '^\s+"image/png".*$'
